### ISSUE TITLE
Implement todo list app using datview

### ISSUE THREAD

**Issue by metasoarous** [metasoarous/catalysis#6]
Should be able to more or less depend on `entity-view` and `edit-entity-form`.

**Comment by Conaws** [comment]
Following just the instructions on the readme I see this

<img width="1280" alt="screenshot 2016-06-03 23 58 16" src="https://cloud.githubusercontent.com/assets/2712495/15788927/6312c27e-29e7-11e6-9fe0-09707e1571d9.png">

I take it I'm supposed to see more than that?

the first time I made the request I got that I was missing favicon for localhost:2358

got this error in figwheel -- could that be the issue?

WARNING: Use of undeclared Var cljs.pprint/pprint at line 40 file:/Users/conor/.m2/repository/datsync/datsync/0.0.1-SNAPSHOT/datsync-0.0.1-SNAPSHOT.jar!/datsync/impl/utils.cljc

**Comment by Conaws** [comment]
Ok, looking more closely at the code it seems like this isn't implemented yet -- might want to include that in the Readme if so.

**Comment by metasoarous** [comment]
Well... it should be implemented. Are you looking at an up to date catalysis? Try pulling. If that's not the problem, my guess is that it's #15.

**Comment by metasoarous** [comment]
I'm closing this issue for now, since we actually do have some level of todo list functionality set up.
